spring.application.name=saft-bndes

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.servlet.context-path=/saft-bndes
spring.web.error.include-stacktrace=never
spring.servlet.multipart.max-file-size=10000MB
spring.servlet.multipart.max-request-size=10000MB
spring.servlet.multipart.enabled=true